accounts/urls.py
from django.conf.urls import url
# from django.contrib.auth.views import view as auth_view
from . import views
from django.conf import settings
from django.conf.urls.static import static
app_name = 'accounts'

urlpatterns = [
    url(r'^citizen/$', views.citizen, name='citizen'),
    url(r'^lawyer/$', views.lawyer, name='lawyer'),
    url(r'^loginpage/$', views.loginpage, name='loginpage'),
    url(r'^login/', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^citizen/signup/$', views.citizensignup, name='citizenSignup'),
    url(r'^lawyer/signup/$', views.lawyer_signup, name='lawyerSignup'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

citizen/urls.py
from django.conf.urls import url
# from django.conf import settings
# from django.conf.urls.static import static
from . import views
import lawyer

app_name = 'citizen'

urlpatterns = [
    url(r'^home/$', views.home, name='home'),
    url(r'^advocates/$', views.advocates, name='advocates'),
    url(r'^post/$', views.post, name='post'),
    url(r'^profile/', views.profile_edit, name='edit'),
]
# if settings.DEBUG:
#     urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

law/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from . import views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.landingpage, name='landing'),
    url(r'^lawyer/', include('lawyer.urls')),
    url(r'^citizen/', include('citizen.urls')),
    url(r'^accounts/', include('accounts.urls')),
    # url(r'^USSD/', include('ussd.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/includes/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
   <div class="container">
        <a class="navbar-brand" href="#">DE~LAW</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup"
            aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-center" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-item nav-link active" href="{% url 'citizen:home' %}">Home</a>
                <a class="nav-item nav-link" href="{% url 'citizen:advocates' %}">Advocates</a>
                <a class="nav-item nav-link" href="{% url 'citizen:post' %}">Create</a>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true"
                        aria-expanded="false">
                        {{request.user}}
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'citizen:edit' %}">Profile</a>
                        <a class="dropdown-item" href="{% url 'citizen:post' %}">Post</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'accounts:logout' %}">Logout</a>
                    </div>
                </li>
            </div>
        </div>
   </div>
</nav>
<br><br>