accounts/urls.py
from django.conf.urls import url
# from django.contrib.auth.views import view as auth_view
from . import views
from django.conf import settings
from django.conf.urls.static import static
app_name = 'accounts'

urlpatterns = [
    url(r'^citizen/$', views.citizen, name='citizen'),
    url(r'^lawyer/$', views.lawyer, name='lawyer'),
    url(r'^loginpage/$', views.loginpage, name='loginpage'),
    url(r'^login/', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^citizen/signup/$', views.citizensignup, name='citizenSignup'),
    url(r'^lawyer/signup/$', views.lawyer_signup, name='lawyerSignup'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

law/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from . import views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.landingpage, name='landing'),
    url(r'^lawyer/', include('lawyer.urls')),
    url(r'^citizen/', include('citizen.urls')),
    url(r'^accounts/', include('accounts.urls')),
    # url(r'^USSD/', include('ussd.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lawyer/urls.py
from django.conf.urls import url, include
from . import views
from django.conf import settings
from django.conf.urls.static import static
app_name = 'lawyer'

urlpatterns = [
    url(r'^$', views.lawyerdashboard, name='lawyerdashboard'),
    url(r'^profile/(\d+)/$', views.profile, name='lawyerprofile'),
    url(r'^edit/', views.edit_profile, name='edit'),
    url(r'cases/', views.lawyercases, name='lawyercases'),
    url(r'new/article', views.newarticle, name='newarticle'),
    url(r'^lawyer_form', views.lawyer_form, name='lawyer_form'),
    url(r'^portal', views.portal, name='portal'),
    url(r'^data$', views.reported, name='lawyers'),
    url(r'^google$', views.google, name='google'),
    url(r'article', views.lawyerarticles, name='articles'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

citizen/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, null=True, on_delete=models.CASCADE,related_name='citizen_info')
    avatar = models.ImageField(upload_to='avatar', blank=True)
    bio = models.TextField(max_length=500, blank=True)
    location = models.CharField(max_length=30, blank=True)
    birth_date = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return self.user.username


class Citizen(models.Model):
    '''
    creating a profile model for each citizen
    '''
    user = models.OneToOneField(settings.AUTH_USER_MODEL,
                                on_delete=models.CASCADE, related_name='citizen_profile')
    first_name = models.CharField(max_length=30, null=True)
    last_name = models.CharField(max_length=30, null=True)

    # def __str__(self):
    #     return self.user


class Post(models.Model):
    PRIMARY = 'pr'
    CASE_CATEGORY = (
        (PRIMARY, 'None'),
        ('Dd', 'Druken disorder'),
        ('Lf', 'Land fraud'),
        ('Rb', 'Robbery'),
        ('Md', 'Murder'),
        ('Fr', 'Fraud'),
        ('Sa', 'Sexual Assault'),
    )
    case_category = models.CharField(
        max_length=2,
        choices=CASE_CATEGORY,
        default=PRIMARY,
    )
    case_number = models.CharField(max_length=12)
    case_description = models.TextField()
    post_date = models.DateTimeField(auto_now_add=True)
    citizen = models.ForeignKey(settings.AUTH_USER_MODEL,
                                on_delete=models.CASCADE)
    def __str__(self):
        return self.case_description

lawyer/models.py
from django.contrib.gis.db import models
from django.conf import settings
from django.core.urlresolvers import reverse
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.auth.models import AbstractUser
import datetime as dt
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from citizen.models import Profile,Citizen
from phonenumber_field.modelfields import PhoneNumberField
import citizen
# Create your model

class Lawyer(models.Model):
    GENERAL = 'GN'
    LAW_CATEGORIES = (
        ('CL','Criminal'),
        ('CE','Corporate'),
        ('FL','Financial'),
        ('ET','Entertainment'),
        ('FY','Family'),
        ('EL','Enviromental'),
        ('AY','Admiralty'),
        (GENERAL,'General'),
    )
    user = models.OneToOneField(settings.AUTH_USER_MODEL,
                                on_delete=models.CASCADE,null=True, related_name='lawyer_profile')
    first_name = models.CharField(max_length=60, null=True)
    last_name = models.CharField(max_length=60, null=True)
    email = models.EmailField(max_length=100)
    date = models.DateTimeField(auto_now_add=True)
    avatar = models.ImageField(upload_to='avatar', blank=True)
    bio = models.TextField(max_length=500, blank=True)
    location = models.PointField(srid=4326, null=True)
    phone = PhoneNumberField(null=True, blank=True)
    objects =  models.GeoManager()
    category = models.CharField(max_length=20,choices = LAW_CATEGORIES,default=GENERAL,)

    def __str__(self):
        return self.user.username

    @receiver(post_save, sender=settings.AUTH_USER_MODEL)
    def create_lawyer_profile(sender, instance, created, **kwargs):
        if created:
            if instance.is_lawyer:
                Lawyer.objects.create(user=instance)
            else:
                citizen.models.Profile.objects.create(user=instance)

    @receiver(post_save, sender=settings.AUTH_USER_MODEL)
    def save_lawyer_profile(sender, instance, **kwargs):
        if instance.is_lawyer:
            instance.lawyer_profile.save()
        else:
            instance.citizen_info.save()

class AllLawyer(models.Model):
    name = models.CharField(max_length=250)
    icon = models.CharField(max_length=250)
    description = models.CharField(max_length=250)

    geom = models.PointField(srid=4326)
    objects = models.GeoManager()


class Articles(models.Model):
    image = ProcessedImageField(
        upload_to='posts/', processors=[ResizeToFill(700, 700)], format='JPEG', options={'quality': 100}, blank=True)
    name = models.CharField(max_length=30)
    post = models.TextField()
    time = models.DateTimeField(auto_now_add=True)
    lawyer = models.ForeignKey(Lawyer, on_delete=models.CASCADE)

lawyer/forms.py
from django import forms
from .models import Articles, Lawyer
from django.forms import ModelForm
from leaflet.forms.widgets import LeafletWidget
from leaflet.forms.fields import PointField
from django import forms


class NewArticleForm(forms.ModelForm):
    class Meta:
        model = Articles
        exclude = ['time', 'lawyer',]


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Lawyer
        exclude = ['user',]

class LawyerForm(forms.ModelForm):
    location = PointField()

    class Meta:
        model = Lawyer
        fields = '__all__'

class DataForm(forms.Form):
    first_name = forms.CharField(max_length=50)
    last_name = forms.CharField(max_length=50)
    phone = forms.CharField(max_length=50, required=True)
    coordinates=forms.CharField(max_length=200, required=True)
    model = Lawyer
    exclude = ['user']

law/views.py
from django.shortcuts import render
import datetime as dt 

# Create your views here.
def landingpage(request):
    return render(request,'landingpage.html')

lawyer/views.py
from lawyer.forms import NewArticleForm, ProfileForm
from django.contrib.auth.decorators import login_required
import datetime as dt
from .models import Articles, Lawyer
from django.shortcuts import render, redirect, reverse
from django.http import HttpResponseRedirect
from django.conf import settings
from django.db import transaction
from django.contrib import messages
from citizen.models import Citizen, Post, Profile

# Create your views here.


def lawyerdashboard(request):
    return render(request, 'law/lawyerdashboard.html')


def lawyercases(request):
    cases = Post.objects.all()
    drunk = Post.objects.filter(case_category ='Dd')
    land = Post.objects.filter(case_category ='Lf')
    robbery = Post.objects.filter(case_category ='Rb')
    murder = Post.objects.filter(case_category ='Md')
    fraud = Post.objects.filter(case_category ='Fr')
    sex = Post.objects.filter(case_category ='Sa')

    return render(request, 'law/viewcase.html',{"cases":cases,"drunk":drunk,"land":land,"robbery":robbery,"murder":murder,"fraud":fraud,"sex":sex})


def lawyerarticles(request):
    articles = Articles.objects.all()
    return render(request, 'law/lawyerarticle.html', {"articles":articles})


def newarticle(request):
    current_user = request.user.lawyer_profile.id
    profile = Lawyer.objects.get(id=current_user)
    if request.method == 'POST':
        form = NewArticleForm(request.POST, request.FILES)
        if form.is_valid():
            article = form.save(commit=False)
            article.lawyer = profile
            article.save()
            # redirect not working return redirect('lawyer:profile)
    else:
        form = NewArticleForm()
    return render(request, 'law/new_post.html', {"form": form})


@login_required(login_url='/accounts/login/')
def profile(request, profile_id):
    current_profile = Lawyer.objects.get(id=profile_id)
    articles = Articles.objects.filter(lawyer=current_profile)
    return render(request, 'law/lawyerprofile.html', {"current_profile": current_profile,"articles":articles})


@transaction.atomic
def edit_profile(request):
    if request.method == 'POST':
        profile_form = ProfileForm(
            request.POST, request.FILES, instance=request.user.lawyer_profile)
        if profile_form.is_valid():
            profile_form.save()
            # messages.success(request, _(
            #     'Your profile was successfully updated!'))
            return redirect('lawyer:lawyerprofile',request.user.lawyer_profile.id)
        else:
            messages.error(request, ('Please correct the error below.'))
    else:
        profile_form = ProfileForm(instance=request.user.lawyer_profile)
    return render(request, 'edit_profile.html', {"profile_form": profile_form})

lawyer/templates/law/base.html
{% load bootstrap4%}
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  {% if title %}
  <title>the law {{title}}</title>
  {% else %}
    <title>the law</title>
  {% endif %}
  {% block styles %}
    {% bootstrap_css %}
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">
  <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="{% static 'css/lawyer.css'%}">
  {% endblock %}
    <script>
      "use strict";
      
      !function () {
        var t = window.driftt = window.drift = window.driftt || [];
        if (!t.init) {
          if (t.invoked) return void (window.console && console.error && console.error("Drift snippet included twice."));
          t.invoked = !0, t.methods = ["identify", "config", "track", "reset", "debug", "show", "ping", "page", "hide", "off", "on"],
            t.factory = function (e) {
              return function () {
                var n = Array.prototype.slice.call(arguments);
                return n.unshift(e), t.push(n), t;
              };
            }, t.methods.forEach(function (e) {
              t[e] = t.factory(e);
            }), t.load = function (t) {
              var e = 3e5, n = Math.ceil(new Date() / e) * e, o = document.createElement("script");
              o.type = "text/javascript", o.async = !0, o.crossorigin = "anonymous", o.src = "https://js.driftt.com/include/" + n + "/" + t + ".js";
              var i = document.getElementsByTagName("script")[0];
              i.parentNode.insertBefore(o, i);
            };
        }
      }();
      drift.SNIPPET_VERSION = '0.3.1';
      drift.load('3z78wr3dfbxc');
    </script>
    <!-- End of Async Drift Code -->
</head>
<body>
    {% include "law/nav.html" %}
    {% block content %}
     {%endblock%}
    {% block scripts %}
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
     {% bootstrap_javascript %}
    {% endblock %}
</body>
</html>

lawyer/templates/law/lawyer.html
{%extends 'law/base.html'%} 
{%block content%}
Hello world
{%endblock%}

lawyer/templates/law/lawyerarticle.html
{% extends 'law/base.html' %}
{% load staticfiles%}
 {% block content %}
 {% block styles %}
  {{block.super}}
  <link rel="stylesheet" href="{% static 'css/lawyer/article.css'%}">
{% endblock %}
<h1 class="text-center">Articles</h1>

<div class="container">
  <section class="criminal">
    <div class="container">
      <h2>Articles</h2>
      <div class="row">
        {% for article in articles %}
        <div class="col-sm-12 col-md-4">
          <div class="card">
            <div class="card-header">
              <p>{{article.name}}</p>
            </div>
            <div class="card-body text-center">
              <img class="card-img-top" src="{{article.image.url}}">
              <p class="card-text text-left">{{article.post}}</p>
            </div>
            <div class="card-footer">
              <p>posted at:{{article.time}}</p>
              <a href="#" class="btn btn-primary">Read more</a>
            </div>
          </div>
        </div>
        {% endfor%}

      </div>
    </div>
  </section>
</div>

{% endblock %}

lawyer/templates/law/lawyerdashboard.html
{% extends 'law/base.html' %}
{% block content %}
    <p>{{request.user}}</p>
<div class="container" style="padding-top:90px;">
    <div class="row">
        <div class="col-md-6">
            bleh

           
            <div class="profile">
                <div class="container">
                    <div class="row">
                        <div class="col-12">
                           hello lawyer 1
                        </div>
                    </div>
                </div>
            </div>
            
           
            <div class="container">
                <div class="row">
                    <div class="col-5">
                      Blah blah blah
                        </a>
                    </div>
                </div>
            </div>
            
        </div>
    </div>
</div>

{% endblock %}

lawyer/templates/law/lawyerprofile.html
{%extends 'law/base.html'%}
{% load staticfiles %}
{% block content %}
{% block styles %}
   {{block.super}}
<link rel="stylesheet" href="{% static 'css/lawyer/profile.css'%}">
{% endblock %}

<div class="container">
  <div class="card profile-body">
    {% if current_profile.user.id == request.user.id%}
      <a class="edit" href="{% url 'lawyer:edit'%}"><span><i class="float-right fa fa-edit fa-2x"></i></span></a>
    {% endif%}
    {% if current_profile.avatar%}
    <img src="{{ current_profile.avatar.url}}" class="text-center rounded-circle profile" alt="avatar">
    {% endif %}
    <h1><span class="bold">{{ current_profile.user.lawyer_profile.first_name }} {{ current_profile.user.lawyer_profile.last_name}}</span></h1>
    {# <p class="bold"> username:{{current_profile.user.username}}</p> #}
    <p>category:  {{ current_profile.category}}</p>
    <p>Bio:{{ current_profile.bio}}</p>
    <p>Location:{{ current_profile.location}}</p>
    <div style="margin: 24px 0;">
     <a href="#"><i class="fa fa-twitter"></i></a>
     <a href="#"><i class="fa fa-linkedin"></i></a>
     <a href="#"><i class="fa fa-facebook"></i></a>
  </div>
  <p><button class="contact">Contact</button></p>
  </div>
</div>

<br><br>


<div class="container">
  <h4 class="text-center">Your Articles</h4>
  <div class="row">
    {% for article in articles %}
    <div class="col-sm-12 col-md-4">
      <div class="card">
        <div class="card-header">
          <p>{{article.name}}</p>
        </div>
        <div class="card-body text-center article_body">
          <img class="card-img-top" src="{{article.image.url}}">
          {# <p class="card-text text-left">{{article.post}}</p> #}
        </div>
        <div class="card-footer">
          <p>posted at:{{article.time}}</p>
          <a href="#" class="btn btn-primary">Read more</a>
        </div>
      </div>
    </div>
    {% endfor%}
  </div>
</div>
</div>
{% endblock %}

lawyer/templates/law/nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">The-law</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

      <li class="nav-item">
        <a class="nav-link" href="{% url 'lawyer:lawyercases'%}">Cases</a>
      </li>

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Articles
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'lawyer:newarticle'%}">Post Article</a>
          <a class="dropdown-item" href="{% url 'lawyer:articles'%}">View Articles</a>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fa fa-user" aria-hidden="true"></i>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'accounts:loginpage'%}">login</a>
          {% if user.is_authenticated %}
          <a class="dropdown-item" href="{% url 'accounts:logout'%}">logout</a>
          <a class="dropdown-item" href="{% url 'lawyer:lawyerprofile' user.lawyer_profile.id%}">View Profile</a>
          {% endif %}
        </div>
      </li>

    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

lawyer/templates/law/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light  nav-custom" style="background-color: #FF0000">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample10" aria-controls="navbarsExample10"
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-md-center" id="navbarsExample10">
        <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="#">Home
                    <span class="sr-only">(current)</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Cases</a>
            </li>
            <li class="nav-item">
                <a class="nav-link " href="#">Articles</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="https://example.com" id="dropdown10" data-toggle="dropdown" aria-haspopup="true"
                    aria-expanded="false">{{ request.user }}</a>
                <div class="dropdown-menu" aria-labelledby="dropdown10">
                    <a class="dropdown-item" href="#">Profile</a>
                    <a class="dropdown-item" href="#">Post Article</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Logout</a>
                </div>
            </li>
        </ul>
    </div>
</nav>

lawyer/templates/law/new_post.html
{%extends 'law/base.html'%}
{%load bootstrap4 %}
{%load staticfiles %}
{%block content%}
<div class="container body-content">
    <div class="row">
        <div class="col-md-6 col-lg-3 col-sm-9 col-xs-12 ">

            <form action="{% url 'lawyer:newarticle' %}" method="post" enctype="multipart/form-data">
                {%csrf_token%}
                 {%bootstrap_form form %}
                <input type="submit" class="btn btn-primary" value="post">
            </form>
        </div>
    </div>
</div>
{%endblock%}

lawyer/templates/law/profile.html
{%extends 'law/base.html'%} 
{%block content%}
Hello profile
{%endblock%}

lawyer/templates/law/viewcase.html
{% extends 'law/base.html' %} {% load staticfiles%} {% block content %} {% block styles %} {{block.super}} {% endblock %} {% block scripts %} {{block.super}}
<script src="{% static 'js/cases.js'%}"></script>
{% endblock %}
<h1 class="text-center">Cases</h1>

<div class="container">
  <section class="drunken">
    <div class="container">
      <h2>Drunken Disorder</h2>
      <div class="row ">
        {% for case in drunk%}
        <div class="col-sm-12 col-md-4 animated zoomIn">
          <div class="card">
            <div class="card-header">
              <p>{{case.get_case_category_display}}</p>
            </div>
            <div class="card-body text-center">
              <h5 class="card-title"></h5>
              <p class="card-text text-left">{{ case.case_description}}</p>
            </div>
            <div class="card-footer">
              <p>{{ case.post_date}}</p>
              <a href="#" class="btn btn-primary">More info</a>
            </div>
          </div>
        </div>
        {% endfor%}
      </div>
    </div>
  </section>
  <section class="land_fraud">
    <div class="container">
      <h2>Land Fraud</h2>
      <div class="row">
        {% for case in land%}
        <div data-aos="flip-left" data-aos-easing="ease-out-cubic" data-aos-duration="2000" class="col-sm-12 col-md-4">
          <div class="card">
            <div class="card-header">
              <p>{{case.get_case_category_display}}</p>
            </div>
            <div class="card-body text-center">
              <h5 class="card-title"></h5>
              <p class="card-text text-left">{{ case.case_description}}</p>
            </div>
            <div class="card-footer">
              <p>{{ case.post_date}}</p>
              <a href="#" class="btn btn-primary">More info</a>
            </div>
          </div>
        </div>
        {% endfor%}
      </div>
    </div>
  </section>
  <section class="robbery">
    <div class="container">
      <h2>Robbery</h2>
      <div class="row">
        {% for case in robbery%}
        <div data-aos="flip-left" data-aos-easing="ease-out-cubic" data-aos-duration="2000" class="col-sm-12 col-md-4">
          <div class="card">
            <div class="card-header">
              <p>{{case.get_case_category_display}}</p>
            </div>
            <div class="card-body text-center">
              <h5 class="card-title"></h5>
              <p class="card-text text-left">{{ case.case_description}}</p>
            </div>
            <div class="card-footer">
              <p>{{ case.post_date}}</p>
              <a href="#" class="btn btn-primary">More info</a>
            </div>
          </div>
        </div>
        {% endfor%}
      </div>
    </div>
  </section>
  <section class="murder">
    <div class="container">
      <h2>Murder</h2>
      <div class="row">
        {% for case in murder%}
        <div data-aos="flip-left" data-aos-easing="ease-out-cubic" data-aos-duration="2000" class="col-sm-12 col-md-4">
          <div class="card">
            <div class="card-header">
              <p>{{case.get_case_category_display}}</p>
            </div>
            <div class="card-body text-center">
              <h5 class="card-title"></h5>
              <p class="card-text text-left">{{ case.case_description}}</p>
            </div>
            <div class="card-footer">
              <p>{{ case.post_date}}</p>
              <a href="#" class="btn btn-primary">More info</a>
            </div>
          </div>
        </div>
        {% endfor%}
      </div>
    </div>
  </section>
  <section class="fraud">
    <div class="container">
      <h2>Fraud</h2>
      <div class="row">
        {% for case in fraud%}
        <div data-aos="flip-left" data-aos-easing="ease-out-cubic" data-aos-duration="2000" class="col-sm-12 col-md-4">
          <div class="card">
            <div class="card-header">
              <p>{{case.get_case_category_display}}</p>
            </div>
            <div class="card-body text-center">
              <h5 class="card-title"></h5>
              <p class="card-text text-left">{{ case.case_description}}</p>
            </div>
            <div class="card-footer">
              <p>{{ case.post_date}}</p>
              <a href="#" class="btn btn-primary">More info</a>
            </div>
          </div>
        </div>
        {% endfor%}
      </div>
    </div>
  </section>
  <section class="sex">
    <div class="container">
      <h2>Sexual Assault</h2>
      <div class="row">
        {% for case in sex%}
        <div data-aos="flip-left" data-aos-easing="ease-out-cubic" data-aos-duration="2000" class="col-sm-12 col-md-4">
          <div class="card">
            <div class="card-header">
              <p>{{case.get_case_category_display}}</p>
            </div>
            <div class="card-body text-center">
              <h5 class="card-title"></h5>
              <p class="card-text text-left">{{ case.case_description}}</p>
            </div>
            <div class="card-footer">
              <p>{{ case.post_date}}</p>
              <a href="#" class="btn btn-primary">More info</a>
            </div>
          </div>
        </div>
        {% endfor%}
      </div>
    </div>
  </section>
</div>

{% endblock %}