accounts/urls.py
from django.conf.urls import url
# from django.contrib.auth.views import view as auth_view
from . import views
from django.conf import settings
from django.conf.urls.static import static
app_name = 'accounts'

urlpatterns = [
    url(r'^citizen/$', views.citizen, name='citizen'),
    url(r'^lawyer/$', views.lawyer, name='lawyer'),
    url(r'^loginpage/$', views.loginpage, name='loginpage'),
    url(r'^login/', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^citizen/signup/$', views.citizensignup, name='citizenSignup'),
    url(r'^lawyer/signup/$', views.lawyer_signup, name='lawyerSignup'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

law/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from . import views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.landingpage, name='landing'),
    url(r'^lawyer/', include('lawyer.urls')),
    url(r'^citizen/', include('citizen.urls')),
    url(r'^accounts/', include('accounts.urls')),
    # url(r'^USSD/', include('ussd.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load staticfiles %}
{% load leaflet_tags %}
{% leaflet_js plugins="forms" %}
{% leaflet_css plugins="forms" %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_messages %}
<html>
    <head>
            <style>
                    #mapdiv {
                        height:100vh;
                    }
                      #divProject{
                          background-color: beige;
                      }
                       .col-xs-12, .col-xs-6, .col-xs-4{
                          padding:3px;
                      }
                      .errorMsg{
                          padding:0;
                          text-align: center;
                          background-color: darksalmon;
                      }
                      .btn-default {
                            background: #0f0f0f;
                            color: #fff;
                        }
                        img {
                              position: relative;
                              top: -3px;
                              left: -3px;
                                   }
        
                </style>
        <title>Incidences reporter</title>
       <link rel="stylesheet" href="{% static 'src/leaflet.css' %}">
        <link rel="stylesheet" href="{% static 'src/jquery-ui.min.css' %}">
        <link rel="stylesheet" href="{% static 'src/bootstrap/css/bootstrap.css' %}">
         <link rel="stylesheet" href="{% static 'src/css/font-awesome.min.css' %}">
          <link rel="stylesheet" href="{% static 'src/plugins/leaflet.awesome-markers.css' %}">
        <link rel="stylesheet" href="{% static 'src/plugins/L.Control.Pan.css' %}">
        <link rel="stylesheet" href="{% static 'src/plugins/L.Control.Zoomslider.css' %}">
        <link rel="stylesheet" href="{% static 'src/plugins/L.Control.MousePosition.css' %}">
        <link rel="stylesheet" href="{% static 'src/plugins/L.Control.Sidebar.css' %}">
        <link rel="stylesheet" href="{% static 'src/plugins/Leaflet.PolylineMeasure.css' %}">

        <link rel="stylesheet" href="{% static 'src/plugins/easy-button.css' %}">
        <link rel="stylesheet" href="{% static 'src/plugins/leaflet-opencage/src/css/L.Control.OpenCageSearch.css' %}">
        <link rel="stylesheet" href="{% static 'src/plugins/leaflet-draw/leaflet.draw.css' %}"/>
        <link rel="stylesheet" href="{% static 'src/plugins/leaflet-styleeditor/css/Leaflet.StyleEditor.css' %}">
        <link rel="stylesheet" href="{% static 'src/css/font-awesome.min.css' %}"/>
        <link rel="stylesheet" href="{% static 'src/plugins/MarkerCluster.Default.css' %}"/>
        <link rel="stylesheet" href="{% static 'src/plugins/MarkerCluster.css' %}"/>
        <link rel="stylesheet" href="{% static 'src/plugins/routing/dist/leaflet-routing-machine.css' %}"/>



      <style>
          #loading {
  position: absolute;
  width: 220px;
  height: 19px;
  top: 50%;
  left: 50%;
  margin: -10px 0 0 -110px;
  z-index: 20001;
}

      </style>
    </head>
    <body>
        <div class="container-fluid">
            {% include 'navbar.html' %}
            
                    {% block content %}
                
                    {% endblock %}
        
       
        </div>
        
    </body>

    <script src="{% static 'src/leaflet-src.js' %}"></script>
    <script src="{% static 'src/bootstrap/js/bootstrap.js' %}"></script>
    <script src="{% static 'src/jquery-3.2.0.min.js' %}"></script>
    <script src="{% static 'src/leaflet-corridor.js' %}"></script>
    <script src="{% static 'src/jquery-ui.min.js' %}"></script>
    <script src="{% static 'src/choropleth.js' %}"></script>
    <script src="{% static 'src/leaflet-heat.js' %}"></script>
    <script src="{% static 'src/AnimatedMarker.js' %}"></script>
    <script src="{% static 'src/plugins/L.Control.Pan.js' %}"></script>
    <script src="{% static 'src/plugins/L.Control.Zoomslider.js' %}"></script>
    <script src="{% static 'src/plugins/L.Control.MousePosition.js' %}"></script>
    <script src="{% static 'src/plugins/leaflet.awesome-markers.min.js' %}"></script>
    <script src="{% static 'src/plugins/L.Control.Sidebar.js' %}"></script>
    <script src="{% static 'src/plugins/Leaflet.PolylineMeasure.js' %}"></script>
    <script src="{% static 'src/plugins/leaflet.ajax.min.js' %}"></script>
    <script src="{% static 'src/plugins/leaflet.geometryutil.js' %}"></script>
     <script src="{% static 'src/turf.min.js' %}"></script>
    <script src="{% static 'src/plugins/easy-button.js' %}"></script>
    <script src="{% static 'src/plugins/leaflet-opencage/src/js/L.Control.OpenCageSearch.js' %}"></script>
    <script src="{% static 'src/plugins/leaflet-providers.js' %}"></script>
     <script src="{% static 'src/plugins/leaflet-styleeditor/javascript/Leaflet.StyleEditor.js' %}"></script>
    <script src="{% static 'src/plugins/leaflet-styleeditor/javascript/Leaflet.StyleForms.js' %}"></script>
    {% comment %} <script src="{% static 'src/plugins/routing/dist/leaflet-routing-machine.js' %}"></script>
     {% endcomment %}
     <link rel="stylesheet" href="https://unpkg.com/leaflet-routing-machine@latest/dist/leaflet-routing-machine.css" />
    <script src="https://unpkg.com/leaflet-routing-machine@latest/dist/leaflet-routing-machine.js"></script>
<!--    ***************  Begin Leaflet.Draw-->

    <script src="{% static 'src/plugins/leaflet-draw/Leaflet.draw.js' %}"></script>
    <script src="{% static 'src/plugins/leaflet-draw/Leaflet.Draw.Event.js' %}"></script>
    <link rel="stylesheet" href="{% static 'src/plugins/leaflet-draw/leaflet.draw.css' %}"/>

    <script src="{% static 'src/plugins/leaflet-draw/Toolbar.js' %}"></script>
    <script src="{% static 'src/plugins/leaflet-draw/Tooltip.js' %}"></script>

    <script src="{% static 'src/plugins/leaflet-draw/ext/GeometryUtil.js' %}"></script>
    <script src="{% static 'src/plugins/leaflet-draw/ext/LatLngUtil.js' %}"></script>
    <script src="{% static 'src/plugins/leaflet-draw/ext/LineUtil.Intersect.js' %}"></script>
    <script src="{% static 'src/plugins/leaflet-draw/ext/Polygon.Intersect.js' %}"></script>
    <script src="{% static 'src/plugins/leaflet-draw/ext/Polyline.Intersect.js' %}"></script>
    <script src="{% static 'src/plugins/leaflet-draw/ext/TouchEvents.js' %}"></script>

    <script src="{% static 'src/plugins/leaflet-draw/draw/DrawToolbar.js' %}"></script>
    <script src="{% static 'src/plugins/leaflet-draw/draw/handler/Draw.Feature.js' %}"></script>
    <script src="{% static 'src/plugins/leaflet-draw/draw/handler/Draw.SimpleShape.js' %}"></script>
    <script src="{% static 'src/plugins/leaflet-draw/draw/handler/Draw.Polyline.js' %}"></script>
    <script src="{% static 'src/plugins/leaflet-draw/draw/handler/Draw.Circle.js' %}"></script>
    <script src="{% static 'src/plugins/leaflet-draw/draw/handler/Draw.Marker.js' %}"></script>
    <script src="{% static 'src/plugins/leaflet-draw/draw/handler/Draw.Polygon.js' %}"></script>
    <script src="{% static 'src/plugins/leaflet-draw/draw/handler/Draw.Rectangle.js' %}"></script>


    <script src="{% static 'src/plugins/leaflet-draw/edit/EditToolbar.js' %}"></script>
    <script src="{% static 'src/plugins/leaflet-draw/edit/handler/EditToolbar.Edit.js' %}"></script>
    <script src="{% static 'src/plugins/leaflet-draw/edit/handler/EditToolbar.Delete.js' %}"></script>

    <script src="{% static 'src/plugins/leaflet-draw/Control.Draw.js' %}"></script>

    <script src="{% static 'src/plugins/leaflet-draw/edit/handler/Edit.Poly.js' %}"></script>
    <script src="{% static 'src/plugins/leaflet-draw/edit/handler/Edit.SimpleShape.js' %}"></script>
    <script src="{% static 'src/plugins/leaflet-draw/edit/handler/Edit.Circle.js' %}"></script>
    <script src="{% static 'src/plugins/leaflet-draw/edit/handler/Edit.Rectangle.js' %}"></script>
    <script src="{% static 'src/plugins/leaflet-draw/edit/handler/Edit.Marker.js' %}"></script>
    <script src="{% static 'src/plugins/leaflet.markercluster.js' %}"></script>
<!--    **************  End of Lealet Draw-->
    <script src="{% static 'js/scripts.js' %}"></script>
    <script src="{% static 'js/incidences.js' %}"></script>

   <script src="http://leaflet.github.io/Leaflet.markercluster/example/realworld.10000.js"></script>
</html>

templates/landingpage.html
{%extends 'landingpage/base.html'%}
      {%block content%}
    <div class="container-fluid">
        <div class="row">
            
                    
            <div class="claim">
                <div class="claim--contents">
                    <h1>The Law </h1>
                    <p class="scream">
                        Find and talk to advocates and lawyers at the go.<br>
                        Easily join our ever expanding community of legal advisors and be in the know about legal issues and your rights
                        </p>
                    <p>
                        <a href="{% url 'accounts:citizenSignup' %}" class="button button-wesley button-pill button-giant">Citizen Signup</a>
                        <a href="{%url 'accounts:lawyerSignup' %}" class="button button-wesley button-pill button-giant">Lawyer Signup</a>

                    </p>
                </div>
            </div>
            
            
            <div class="container" id="go">
            
                <div class="row">
                    <div class="col-md-4 ">
                        <h1>Geo Mapping</h1>
                        <p>We connect you to the legal team of Kenya both freelance agents and firms around you based on your location
                            through the use of state of the art google maps technology making the process of getting a lawyer easier
                        </p>
                        <p>
                            <a href="#" class="button button-pill button-wesley">Read more
                                <i class="fa fa-angle-right"></i>
                            </a>
                        </p>
                    </div>
                    <div class="col-md-4 ">
                        <h1>Legal advice</h1>
                        <p>Only the best of the best apply to become lawyers or advocates into our app ensuring that the legal advice one gets is sound and 
                            of the highest quality available. Like Nakumatt... You need it we've got it
                        </p>
                        <p>
                            <a href="#" class="button button-pill button-wesley">Read more
                                <i class="fa fa-angle-right"></i>
                            </a>
                        </p>
                    </div>
                    <div class="col-md-4 ">
                        <h1>Mobile USSD</h1>
                        <p>The USSD platform incorporates all that one requires from our site in a
                            way in which one can get all the information from the ease of their phones even in the rural areas with our USSD code hosted with details you may need.
                            
                        </p>
                        <p>
                            <a href="#" class="button button-pill button-wesley">Read more
                                <i class="fa fa-angle-right"></i>
                            </a>
                        </p>
                    </div>
                   
                </div>
            
            </div>

            
            <div class="claim">
                <div class="claim--contents" id="other-picture">
                    <h1>One on One Personal Time with lawyers</h1>
                    <h2 > We make your legal matters our business and provide information out there for all to see and use</h2>
                    
                        <a href="{% url 'accounts:citizenSignup' %}" class="button button-wesley button-pill button-giant">See the Lawyers</a>
                </div>
            </div>
            
            
            <div class="container" id="go2">
            
                <div class="grid grid-pad">
                    <div class="col-1-3">
                        <p>
                           
                        </p>
                    </div>
                    <div class="col-2-3">
                        <h1>Articles that keep you in touch with legal matters</h1>
                        <p>We believe in information distribution to everyone and encourage lawyers signed into the application to write articles that are then previewed as a news feed on the users dashboard.
                            The User will then be empowered to know about legal matters and have at least some idea on how legal matters work and their rights and priviledges as citizens.
                            From a lawyer perspective, the lawyers express themselves and do their ethical duty to distribute information to the citizens who they server according to their calling  

                        </p>
            
                        <p>Sample articles and how the interface looks like are down below 
                            </p>
                        <p>
                            <a href="#" target="_blank" class="button button-pill button-wesley">Hottest in the market
                                <i class="fa fa-thermometer-three-quarters"></i>
                            </a>
                        </p>
                        <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                            <ol class="carousel-indicators">
                                <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                                <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                                <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                            </ol>
                            <div class="carousel-inner">
                                <div class="carousel-item active">
                                    <img class="d-block w-100" src="..." alt="First slide">
                                </div>
                                <div class="carousel-item">
                                    <img class="d-block w-100" src="..." alt="Second slide">
                                </div>
                                <div class="carousel-item">
                                    <img class="d-block w-100" src="..." alt="Third slide">
                                </div>
                            </div>
                            <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                <span class="sr-only">Previous</span>
                            </a>
                            <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                <span class="sr-only">Next</span>
                            </a>
                        </div>
                    </div>
                </div>
            
                <div class="grid grid-pad">
                    <div class="col-2-3">
                        <h1>Ever Expanding Community</h1>
                        <p>
                            De law has an ever expanding community of both legal staff who provide legal advice and services on the application which ensures that you are safe and are always ahead of the pact in terms of legal matters.
                            
                        </p>
            
                        <p>
                            The website is strongly found on the principles of transparency and right to knowledge.
                        </p>
                        <p>
                        </p>
                    </div>
                </div>
            
            </div>
            
            
           
                        
        </div>
                <footer>
                    <div class="row">
                        <div class="col-md-4">
                            <ul>
                                <li>
                                    <a href="#">Company</a>
                                </li>
                                <li>
                                    <a href="#">Team</a>
                                </li>
                                <li>
                                    <a href="#">References</a>
                                </li>
                                <li>
                                    <a href="#">Whitepapers</a>
                                </li>
                            </ul>
                        </div>
                        <div class="col-md-4">
                            <ul>
                                <li>
                                    <a href="#">Overview</a>
                                </li>
                                <li>
                                    <a href="#">Chatbot</a>
                                </li>
                                <li>
                                    <a href="#">Github code</a>
                                </li>
                                <li>
                                    <a href="#">Community</a>
                                </li>
                                
                            </ul>
                        </div>
                        <div class="col-md-4">
                            <ul>
                                <li>
                                    <a href="#">Help Center</a>
                                </li>
                                <li>
                                    <a href="#">Statement of Support</a>
                                </li>
                                <li>
                                    <a href="#">Managed Services</a>
                                </li>
                                <li>
                                    <a href="#">About</a>
                                </li>
                                <li>&copy; 2018 Wesley Mutwiri</li>
                            </ul>
                        </footer>
                    
                        
    </div>
</div>
</div>
</div>


{%endblock%}

templates/map_base.html
{% load staticfiles %}
{% load leaflet_tags %}
{% leaflet_js plugins="forms" %}
{% leaflet_css plugins="forms" %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_messages %}
<html>
    <head>
            <style>
                    #mapdiv {
                        height:100vh;
                    }
                      #divProject{
                          background-color: beige;
                      }
                       .col-xs-12, .col-xs-6, .col-xs-4{
                          padding:3px;
                      }
                      .errorMsg{
                          padding:0;
                          text-align: center;
                          background-color: darksalmon;
                      }
                      .btn-default {
                            background: #0f0f0f;
                            color: #fff;
                        }
                        img {
                              position: relative;
                              top: -3px;
                              left: -3px;
                                   }
        
                </style>
        <title>Incidences reporter</title>
       <link rel="stylesheet" href="{% static 'src/leaflet.css' %}">
        <link rel="stylesheet" href="{% static 'src/jquery-ui.min.css' %}">
        <link rel="stylesheet" href="{% static 'src/bootstrap/css/bootstrap.css' %}">
         <link rel="stylesheet" href="{% static 'src/css/font-awesome.min.css' %}">
          <link rel="stylesheet" href="{% static 'src/plugins/leaflet.awesome-markers.css' %}">
        <link rel="stylesheet" href="{% static 'src/plugins/L.Control.Pan.css' %}">
        <link rel="stylesheet" href="{% static 'src/plugins/L.Control.Zoomslider.css' %}">
        <link rel="stylesheet" href="{% static 'src/plugins/L.Control.MousePosition.css' %}">
        <link rel="stylesheet" href="{% static 'src/plugins/L.Control.Sidebar.css' %}">
        <link rel="stylesheet" href="{% static 'src/plugins/Leaflet.PolylineMeasure.css' %}">

        <link rel="stylesheet" href="{% static 'src/plugins/easy-button.css' %}">
        <link rel="stylesheet" href="{% static 'src/plugins/leaflet-opencage/src/css/L.Control.OpenCageSearch.css' %}">
        <link rel="stylesheet" href="{% static 'src/plugins/leaflet-draw/leaflet.draw.css' %}"/>
        <link rel="stylesheet" href="{% static 'src/plugins/leaflet-styleeditor/css/Leaflet.StyleEditor.css' %}">
        <link rel="stylesheet" href="{% static 'src/css/font-awesome.min.css' %}"/>
        <link rel="stylesheet" href="{% static 'src/plugins/MarkerCluster.Default.css' %}"/>
        <link rel="stylesheet" href="{% static 'src/plugins/MarkerCluster.css' %}"/>
        <link rel="stylesheet" href="{% static 'src/plugins/routing/dist/leaflet-routing-machine.css' %}"/>



      <style>
          #loading {
  position: absolute;
  width: 220px;
  height: 19px;
  top: 50%;
  left: 50%;
  margin: -10px 0 0 -110px;
  z-index: 20001;
}

      </style>
    </head>
    <body>
        <div class="container-fluid">
            {% include 'navbar.html' %}
            
                    {% block content %}
                
                    {% endblock %}
        
       
        </div>
        
    </body>

    <script src="{% static 'src/leaflet-src.js' %}"></script>
    <script src="{% static 'src/bootstrap/js/bootstrap.js' %}"></script>
    <script src="{% static 'src/jquery-3.2.0.min.js' %}"></script>
    <script src="{% static 'src/leaflet-corridor.js' %}"></script>
    <script src="{% static 'src/jquery-ui.min.js' %}"></script>
    <script src="{% static 'src/choropleth.js' %}"></script>
    <script src="{% static 'src/leaflet-heat.js' %}"></script>
    <script src="{% static 'src/AnimatedMarker.js' %}"></script>
    <script src="{% static 'src/plugins/L.Control.Pan.js' %}"></script>
    <script src="{% static 'src/plugins/L.Control.Zoomslider.js' %}"></script>
    <script src="{% static 'src/plugins/L.Control.MousePosition.js' %}"></script>
    <script src="{% static 'src/plugins/leaflet.awesome-markers.min.js' %}"></script>
    <script src="{% static 'src/plugins/L.Control.Sidebar.js' %}"></script>
    <script src="{% static 'src/plugins/Leaflet.PolylineMeasure.js' %}"></script>
    <script src="{% static 'src/plugins/leaflet.ajax.min.js' %}"></script>
    <script src="{% static 'src/plugins/leaflet.geometryutil.js' %}"></script>
     <script src="{% static 'src/turf.min.js' %}"></script>
    <script src="{% static 'src/plugins/easy-button.js' %}"></script>
    <script src="{% static 'src/plugins/leaflet-opencage/src/js/L.Control.OpenCageSearch.js' %}"></script>
    <script src="{% static 'src/plugins/leaflet-providers.js' %}"></script>
     <script src="{% static 'src/plugins/leaflet-styleeditor/javascript/Leaflet.StyleEditor.js' %}"></script>
    <script src="{% static 'src/plugins/leaflet-styleeditor/javascript/Leaflet.StyleForms.js' %}"></script>
    {% comment %} <script src="{% static 'src/plugins/routing/dist/leaflet-routing-machine.js' %}"></script>
     {% endcomment %}
     <link rel="stylesheet" href="https://unpkg.com/leaflet-routing-machine@latest/dist/leaflet-routing-machine.css" />
    <script src="https://unpkg.com/leaflet-routing-machine@latest/dist/leaflet-routing-machine.js"></script>
<!--    ***************  Begin Leaflet.Draw-->

    <script src="{% static 'src/plugins/leaflet-draw/Leaflet.draw.js' %}"></script>
    <script src="{% static 'src/plugins/leaflet-draw/Leaflet.Draw.Event.js' %}"></script>
    <link rel="stylesheet" href="{% static 'src/plugins/leaflet-draw/leaflet.draw.css' %}"/>

    <script src="{% static 'src/plugins/leaflet-draw/Toolbar.js' %}"></script>
    <script src="{% static 'src/plugins/leaflet-draw/Tooltip.js' %}"></script>

    <script src="{% static 'src/plugins/leaflet-draw/ext/GeometryUtil.js' %}"></script>
    <script src="{% static 'src/plugins/leaflet-draw/ext/LatLngUtil.js' %}"></script>
    <script src="{% static 'src/plugins/leaflet-draw/ext/LineUtil.Intersect.js' %}"></script>
    <script src="{% static 'src/plugins/leaflet-draw/ext/Polygon.Intersect.js' %}"></script>
    <script src="{% static 'src/plugins/leaflet-draw/ext/Polyline.Intersect.js' %}"></script>
    <script src="{% static 'src/plugins/leaflet-draw/ext/TouchEvents.js' %}"></script>

    <script src="{% static 'src/plugins/leaflet-draw/draw/DrawToolbar.js' %}"></script>
    <script src="{% static 'src/plugins/leaflet-draw/draw/handler/Draw.Feature.js' %}"></script>
    <script src="{% static 'src/plugins/leaflet-draw/draw/handler/Draw.SimpleShape.js' %}"></script>
    <script src="{% static 'src/plugins/leaflet-draw/draw/handler/Draw.Polyline.js' %}"></script>
    <script src="{% static 'src/plugins/leaflet-draw/draw/handler/Draw.Circle.js' %}"></script>
    <script src="{% static 'src/plugins/leaflet-draw/draw/handler/Draw.Marker.js' %}"></script>
    <script src="{% static 'src/plugins/leaflet-draw/draw/handler/Draw.Polygon.js' %}"></script>
    <script src="{% static 'src/plugins/leaflet-draw/draw/handler/Draw.Rectangle.js' %}"></script>


    <script src="{% static 'src/plugins/leaflet-draw/edit/EditToolbar.js' %}"></script>
    <script src="{% static 'src/plugins/leaflet-draw/edit/handler/EditToolbar.Edit.js' %}"></script>
    <script src="{% static 'src/plugins/leaflet-draw/edit/handler/EditToolbar.Delete.js' %}"></script>

    <script src="{% static 'src/plugins/leaflet-draw/Control.Draw.js' %}"></script>

    <script src="{% static 'src/plugins/leaflet-draw/edit/handler/Edit.Poly.js' %}"></script>
    <script src="{% static 'src/plugins/leaflet-draw/edit/handler/Edit.SimpleShape.js' %}"></script>
    <script src="{% static 'src/plugins/leaflet-draw/edit/handler/Edit.Circle.js' %}"></script>
    <script src="{% static 'src/plugins/leaflet-draw/edit/handler/Edit.Rectangle.js' %}"></script>
    <script src="{% static 'src/plugins/leaflet-draw/edit/handler/Edit.Marker.js' %}"></script>
    <script src="{% static 'src/plugins/leaflet.markercluster.js' %}"></script>
<!--    **************  End of Lealet Draw-->
    <script src="{% static 'js/scripts.js' %}"></script>
    <script src="{% static 'js/incidences.js' %}"></script>

   <script src="http://leaflet.github.io/Leaflet.markercluster/example/realworld.10000.js"></script>
</html>